// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxaMg3PiddQcRX5oGV8EVZ6JeMPjuCPxo',
    appId: '1:976688896745:web:968232ffd595d8576f6e78',
    messagingSenderId: '976688896745',
    projectId: 'cheetah-c6b84',
    authDomain: 'cheetah-c6b84.firebaseapp.com',
    storageBucket: 'cheetah-c6b84.appspot.com',
    measurementId: 'G-7DYC4SNRQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzJBvRo26U2OP62aTDIzCdQlG1kYkPMfw',
    appId: '1:976688896745:android:152d49f6354becdc6f6e78',
    messagingSenderId: '976688896745',
    projectId: 'cheetah-c6b84',
    storageBucket: 'cheetah-c6b84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdz-QMkWAaOrAMb_MQBtcvf_Vn4MuhS40',
    appId: '1:976688896745:ios:f4b0f7db38a781ee6f6e78',
    messagingSenderId: '976688896745',
    projectId: 'cheetah-c6b84',
    storageBucket: 'cheetah-c6b84.appspot.com',
    iosClientId: '976688896745-4ocnrjmqd3k6kba9ppt48m6ma7mfaunl.apps.googleusercontent.com',
    iosBundleId: 'com.ademercan.cheetah',
  );
}
